export const mockJobs = [
  {
    id: "1",
    title: "MERN Stack Event Management Web App - Calendar & Booking Features",
    postedTime: "40 minutes ago",
    pricing: "Fixed price",
    budget: "$100.00",
    level: "Intermediate",
    description:
      "We need a full-stack developer to build an event management web application with calendar integration and booking features. Must have experience with React, Node.js, and MongoDB.",
    skills: ["JavaScript", "Next.js", "Node.js", "Frontend Developer"],
    paymentVerified: true,
    rating: 4.8,
    hireRate: 69,
    openJobs: 2,
    totalSpend: 30,
    totalHires: 68,
    avgRate: 16.57,
    matchScore: 85,
  },
  {
    id: "2",
    title: "AI Automated Client Acquisition System Setup",
    postedTime: "1 hour ago",
    pricing: "Fixed price",
    budget: "$500.00",
    level: "Advanced",
    description:
      "Looking for an experienced developer to set up an AI-powered client acquisition system. Should integrate with CRM and email marketing platforms.",
    skills: ["Python", "AI/ML", "API Integration", "Backend Developer"],
    paymentVerified: true,
    rating: 4.9,
    hireRate: 75,
    openJobs: 1,
    totalSpend: 50,
    totalHires: 120,
    avgRate: 25.0,
    matchScore: 72,
  },
  {
    id: "3",
    title: "React Dashboard with Real-time Data Visualization",
    postedTime: "2 hours ago",
    pricing: "Hourly",
    budget: "$50-75/hr",
    level: "Intermediate",
    description:
      "Need a React developer to create a dashboard with real-time data visualization using charts and graphs. Must be familiar with D3.js or Recharts.",
    skills: ["React", "TypeScript", "Data Visualization", "Frontend Developer"],
    paymentVerified: true,
    rating: 4.7,
    hireRate: 68,
    openJobs: 3,
    totalSpend: 25,
    totalHires: 45,
    avgRate: 60.0,
    matchScore: 65,
  },
  {
    id: "4",
    title: "WordPress Plugin Development for E-commerce",
    postedTime: "3 hours ago",
    pricing: "Fixed price",
    budget: "$800.00",
    level: "Intermediate",
    description:
      "Develop a custom WordPress plugin for e-commerce functionality. Must integrate with WooCommerce and payment gateways.",
    skills: ["PHP", "WordPress", "WooCommerce", "Backend Developer"],
    paymentVerified: true,
    rating: 4.6,
    hireRate: 72,
    openJobs: 2,
    totalSpend: 40,
    totalHires: 85,
    avgRate: 35.0,
    matchScore: 45,
  },
]

export const mockProfiles = [
  {
    id: "1",
    name: "Jacob Jones",
    title: "Full Stack Developer",
    hourlyRate: "$65/hr",
    experience: "6+ Years",
    jobSuccess: "100%",
  },
  {
    id: "2",
    name: "Sarah Smith",
    title: "React Specialist",
    hourlyRate: "$75/hr",
    experience: "5+ Years",
    jobSuccess: "98%",
  },
  {
    id: "3",
    name: "Michael Chen",
    title: "Backend Engineer",
    hourlyRate: "$80/hr",
    experience: "7+ Years",
    jobSuccess: "99%",
  },
  {
    id: "4",
    name: "Emma Wilson",
    title: "UI/UX Designer",
    hourlyRate: "$55/hr",
    experience: "4+ Years",
    jobSuccess: "97%",
  },
  {
    id: "5",
    name: "David Brown",
    title: "DevOps Engineer",
    hourlyRate: "$85/hr",
    experience: "8+ Years",
    jobSuccess: "100%",
  },
  {
    id: "6",
    name: "Lisa Anderson",
    title: "Data Scientist",
    hourlyRate: "$90/hr",
    experience: "6+ Years",
    jobSuccess: "96%",
  },
  {
    id: "7",
    name: "James Taylor",
    title: "Mobile Developer",
    hourlyRate: "$70/hr",
    experience: "5+ Years",
    jobSuccess: "95%",
  },
  {
    id: "8",
    name: "Rachel Green",
    title: "QA Engineer",
    hourlyRate: "$60/hr",
    experience: "4+ Years",
    jobSuccess: "98%",
  },
]

export const mockTemplates = [
  {
    id: "1",
    title: "AI Integration Engineer | AI Automation Workflows, Python...",
    description:
      "Developed scalable applications with the MERN stack and implemented end-to-end workflow automation using tools like Zapier...",
    icon: "🤖",
  },
  {
    id: "2",
    title: "Full Stack Developer | React, Node.js, MongoDB",
    description:
      "Experienced in building complete web applications from frontend to backend. Proficient in modern JavaScript frameworks and databases.",
    icon: "💻",
  },
  {
    id: "3",
    title: "UI/UX Designer | Figma, Prototyping, User Research",
    description:
      "Specialized in creating beautiful and intuitive user interfaces. Strong background in user research and design systems.",
    icon: "🎨",
  },
  {
    id: "4",
    title: "DevOps Engineer | Docker, Kubernetes, AWS",
    description:
      "Expert in cloud infrastructure and containerization. Experienced with CI/CD pipelines and infrastructure as code.",
    icon: "⚙️",
  },
  {
    id: "5",
    title: "Data Scientist | Python, Machine Learning, Analytics",
    description:
      "Specialized in data analysis and machine learning models. Experienced with TensorFlow, scikit-learn, and data visualization.",
    icon: "📊",
  },
  {
    id: "6",
    title: "Mobile Developer | React Native, Flutter, iOS/Android",
    description:
      "Expert in cross-platform mobile development. Experienced with native and hybrid mobile application development.",
    icon: "📱",
  },
]
